import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Radio, ShieldCheck } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";

export default function CreatorEvents() {
  const [accessType, setAccessType] = useState<"members" | "ticketed" | "private">("members");
  const status = trpc.creator.publishingStatus.useQuery();
  const createEvent = trpc.creator.createLiveEvent.useMutation({ onSuccess: event => toast.success(`Live event #${event.id} scheduled.`), onError: error => toast.error(error.message) });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); createEvent.mutate({ title: String(form.get("title")), description: String(form.get("description") || "") || undefined, accessType, scheduledStartAt: new Date(String(form.get("scheduledStartAt"))), scheduledEndAt: form.get("scheduledEndAt") ? new Date(String(form.get("scheduledEndAt"))) : undefined }); };
  if (!status.data?.enabled) return <DashboardLayout><div className="mx-auto max-w-2xl px-2 py-10"><div className="border border-white/[0.1] bg-white/[0.025] p-8"><ShieldCheck className="h-6 w-6 text-pink-300" /><h1 className="mt-5 font-blackletter text-4xl">Approval required</h1><p className="mt-4 text-sm leading-7 text-zinc-500">Live-event scheduling opens after creator verification and payout readiness are confirmed.</p></div></div></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-3xl px-2 py-5 sm:px-5 sm:py-8"><p className="text-[10px] font-medium uppercase tracking-[.18em] text-pink-300">Creator live events</p><h1 className="mt-3 font-blackletter text-4xl">Set the room.</h1><p className="mt-3 text-sm leading-7 text-zinc-500">Schedule first. A managed live-video provider, moderation assignment, and entry policy must be ready before an event goes live.</p><form onSubmit={submit} className="mt-8 border border-white/[0.1] bg-white/[0.025] p-6"><div><Label htmlFor="event-title">Event title</Label><Input id="event-title" name="title" required maxLength={180} className="mt-2 rounded-sm border-white/[0.12] bg-zinc-950" /></div><div className="mt-5"><Label htmlFor="event-description">Event note</Label><Textarea id="event-description" name="description" maxLength={5000} className="mt-2 min-h-28 rounded-sm border-white/[0.12] bg-zinc-950" /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="event-start">Start time</Label><Input id="event-start" name="scheduledStartAt" type="datetime-local" required className="mt-2 rounded-sm border-white/[0.12] bg-zinc-950" /></div><div><Label htmlFor="event-end">End time</Label><Input id="event-end" name="scheduledEndAt" type="datetime-local" className="mt-2 rounded-sm border-white/[0.12] bg-zinc-950" /></div></div><div className="mt-5"><Label>Entry policy</Label><div className="mt-2 grid gap-2 sm:grid-cols-3">{[{id:"members",name:"Creator members",copy:"Current creator membership"},{id:"ticketed",name:"Ticketed",copy:"Event entitlement"},{id:"private",name:"Private",copy:"Owner/staff only"}].map(item => <button type="button" key={item.id} onClick={() => setAccessType(item.id as typeof accessType)} className={`border p-4 text-left ${accessType === item.id ? "border-pink-300/60 bg-pink-300/[0.08]" : "border-white/[0.1]"}`}><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-zinc-600">{item.copy}</p></button>)}</div></div><div className="mt-6 flex items-start gap-3 border-l border-pink-300/50 pl-4 text-xs leading-6 text-zinc-500"><Radio className="mt-1 h-4 w-4 shrink-0 text-pink-300" />No broadcast credential is issued by this scheduling step. The platform must validate Premium Access plus member or ticket entitlement before the configured video provider receives a request for a short-lived viewer token.</div><Button type="submit" disabled={createEvent.isPending} className="mt-7 rounded-sm border border-pink-300/35 bg-pink-300/[0.12] text-pink-100 hover:bg-pink-300/[0.2]"><CalendarDays className="mr-2 h-4 w-4" />{createEvent.isPending ? "Scheduling…" : "Schedule event"}</Button></form></div></DashboardLayout>;
}
