import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { MessageCircleMore, Search, ShieldAlert } from "lucide-react";

export default function Inbox() {
  const { user } = useAuth();
  return <DashboardLayout><div className="mx-auto grid max-w-6xl gap-5 px-2 py-5 sm:px-5 sm:py-8 lg:grid-cols-[290px_1fr]"><aside className="rounded-3xl border bg-card p-4"><div className="flex items-center justify-between px-2 py-2"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-rose-500">Inbox</p><h1 className="mt-1 text-xl font-semibold">Conversations</h1></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-muted"><MessageCircleMore className="h-4 w-4 text-muted-foreground" /></span></div><label className="mt-5 flex items-center gap-2 rounded-xl border bg-muted/40 px-3"><Search className="h-4 w-4 text-muted-foreground" /><Input className="border-0 bg-transparent px-0 shadow-none focus-visible:ring-0" placeholder="Search messages" aria-label="Search messages" /></label><div className="mt-5 rounded-2xl border border-dashed px-4 py-10 text-center"><p className="text-sm font-medium">No conversations yet</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Conversations appear when a creator’s message setting permits contact.</p></div></aside><section className="flex min-h-[430px] flex-col items-center justify-center rounded-3xl border bg-card p-8 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-rose-500/10 text-rose-500"><MessageCircleMore className="h-6 w-6" /></span><h2 className="mt-5 text-xl font-semibold">Direct connection, clear controls.</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Messages remain between the creator and fan accounts in the conversation. Either side can report content; a restricted account cannot start new messages.</p><div className="mt-6 flex items-center gap-2 rounded-full border bg-muted/40 px-4 py-2 text-xs text-muted-foreground"><ShieldAlert className="h-3.5 w-3.5" />Account role: {user?.role ?? "fan"}</div><Button variant="outline" className="mt-5 rounded-xl">Review messaging settings</Button></section></div></DashboardLayout>;
}
