import { SiteHeader } from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { CalendarDays, Clock3, LockKeyhole, MessageCircle, Radio, ShieldCheck, Ticket } from "lucide-react";

export default function LiveLobby() {
  return <div className="min-h-screen bg-[#0b0a10] text-white"><SiteHeader /><main className="container py-10 sm:py-14"><div className="grid gap-7 lg:grid-cols-[1.2fr_.8fr]"><section className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.035]"><div className="relative aspect-video bg-[radial-gradient(circle_at_70%_20%,rgba(244,114,182,.42),transparent_25%),linear-gradient(130deg,#241329,#291d54_50%,#0b0a10)]"><div className="absolute inset-0 grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-full border border-white/20 bg-zinc-950/50 backdrop-blur"><Radio className="h-8 w-8 text-rose-300" /></div></div><span className="absolute left-5 top-5 rounded-full border border-white/15 bg-zinc-950/60 px-3 py-1.5 text-xs text-zinc-300 backdrop-blur">Live event preview</span></div><div className="p-6 sm:p-8"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-rose-400/15 px-2.5 py-1 font-medium text-rose-200">Members’ entry</span><span className="rounded-full bg-white/8 px-2.5 py-1 text-zinc-400">Managed video provider required</span></div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Open studio session</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-zinc-400">A live event page checks the viewer’s membership, ticket, or creator ownership before it issues playback credentials. This preview does not start a broadcast or expose a stream URL.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => startLogin()} className="rounded-xl bg-white text-zinc-900 hover:bg-zinc-200"><LockKeyhole className="mr-2 h-4 w-4" />Sign in to check access</Button><Button variant="outline" className="rounded-xl border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white"><Ticket className="mr-2 h-4 w-4" />View entry options</Button></div></div></section><aside className="space-y-4"><EventDetail icon={<CalendarDays className="h-4 w-4" />} label="Schedule" value="Set by the creator" /><EventDetail icon={<Clock3 className="h-4 w-4" />} label="Duration" value="Available from provider metadata" /><EventDetail icon={<MessageCircle className="h-4 w-4" />} label="Live chat" value="Moderated by creator settings and platform policy" /><div className="rounded-3xl border border-emerald-300/15 bg-emerald-300/[0.05] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><div><p className="font-medium">Access before playback</p><p className="mt-2 text-sm leading-6 text-zinc-400">Playback tokens are short-lived, creator-scoped, and only issued after an active entitlement check.</p></div></div></div></aside></div></main></div>;
}

function EventDetail({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[0.07] text-rose-200">{icon}</span><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">{label}</p><p className="mt-2 text-sm leading-6 text-zinc-300">{value}</p></div>; }
