import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Flag, Image, Megaphone, ShieldAlert } from "lucide-react";

export default function OperationsDesk() {
  const summary = trpc.operations.summary.useQuery();
  if (summary.isError) return <DashboardLayout><EmptyState title="Operations access required" copy="Creator approval, moderation, and advertising approval are restricted to assigned active staff roles." /></DashboardLayout>;
  const stats = summary.data ? [{ icon: <BadgeCheck className="h-5 w-5" />, label: "Creator applications", value: summary.data.creatorApplications, note: "Submitted applications awaiting administrator review." }, { icon: <Flag className="h-5 w-5" />, label: "Open reports", value: summary.data.openReports, note: "Safety reports awaiting triage or outcome." }, { icon: <Image className="h-5 w-5" />, label: "Pending media", value: summary.data.pendingAssets, note: "Creator assets are unavailable pending moderation." }, { icon: <Megaphone className="h-5 w-5" />, label: "Ad reviews", value: summary.data.pendingAds, note: "Promotions must be disclosed and approved before display." }] : [];
  return <DashboardLayout><div className="mx-auto max-w-5xl space-y-7 px-2 py-5 sm:px-5 sm:py-8"><div><p className="text-[10px] font-medium uppercase tracking-[.16em] text-pink-300">Operations desk</p><h1 className="mt-3 font-blackletter text-4xl">Review with care.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-600">Operational queues contain real system counts only. Each approval, rejection, restriction, and moderation outcome is protected by staff role checks and recorded to the audit log.</p></div>{summary.isLoading ? <div className="grid gap-3 md:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-44 animate-pulse border border-white/[0.08] bg-white/[0.025]" />)}</div> : <section className="grid gap-3 md:grid-cols-4">{stats.map(stat => <article key={stat.label} className="border border-white/[0.1] bg-white/[0.025] p-5"><span className="grid h-9 w-9 place-items-center rounded-sm bg-pink-300/[0.08] text-pink-200">{stat.icon}</span><p className="mt-5 text-[10px] font-medium uppercase tracking-[.14em] text-zinc-600">{stat.label}</p><p className="mt-2 text-3xl font-medium text-white">{stat.value}</p><p className="mt-3 text-xs leading-5 text-zinc-600">{stat.note}</p></article>)}</section>}<section className="border-l border-pink-300/50 bg-pink-300/[0.035] px-5 py-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-pink-200" /><div><h2 className="font-medium text-white">High-risk action standard</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-zinc-500">Verification decisions, report outcomes, content approvals, advertising decisions, account restrictions, and financial adjustments should record the actor, policy basis, target, timestamp, and reversible or appeal path where policy requires it. Sensitive identity and consent evidence must remain in the approved restricted evidence system.</p></div></div></section></div></DashboardLayout>;
}
function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="mx-auto max-w-2xl px-2 py-10"><div className="border border-white/[0.1] bg-white/[0.025] p-8"><ShieldAlert className="h-6 w-6 text-pink-300" /><h1 className="mt-5 font-blackletter text-4xl">{title}</h1><p className="mt-4 text-sm leading-7 text-zinc-600">{copy}</p></div></div>; }
