import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { BadgeCheck, CheckCircle2, Flag, Megaphone, ShieldAlert } from "lucide-react";

export default function OperationsDesk() {
  const { user } = useAuth();
  const permitted = user?.role === "moderator" || user?.role === "admin" || user?.role === "finance";
  if (!permitted) return <DashboardLayout><div className="mx-auto max-w-2xl px-2 py-10"><div className="rounded-3xl border bg-card p-8"><ShieldAlert className="h-6 w-6 text-rose-500" /><h1 className="mt-5 text-2xl font-semibold">Operations access required</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Moderation, finance, and administrative workspaces are restricted to appropriately assigned, active staff accounts.</p></div></div></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-5xl space-y-7 px-2 py-5 sm:px-5 sm:py-8"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-rose-500">Operations desk</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Review with an accountable trail.</h1><p className="mt-2 text-sm text-muted-foreground">Sensitive decisions are scoped to role, subject, and action. This interface deliberately presents no invented reports or user data.</p></div><section className="grid gap-4 md:grid-cols-3"><OperationsCard icon={<Flag className="h-5 w-5" />} title="Moderation queue" copy="Reported resources appear here with priority, context, and documented outcome requirements." button="Open report queue" /><OperationsCard icon={<Megaphone className="h-5 w-5" />} title="Sponsored placements" copy="Promotions require disclosure text, approval status, and consent-aware targeting before display." button="Review placements" /><OperationsCard icon={<BadgeCheck className="h-5 w-5" />} title="Creator applications" copy="Account and payout-readiness checks must complete before creator monetization is activated." button="Review applications" /></section><section className="rounded-3xl border bg-card p-6"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-500" /><div><h2 className="font-semibold">Decision hygiene</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Every enforcement or approval action is recorded against the actor, target, rationale, and time. Refund and payout changes should require the corresponding finance or administrative authority.</p><Button variant="outline" className="mt-5 rounded-xl">View audit activity</Button></div></div></section></div></DashboardLayout>;
}

function OperationsCard({ icon, title, copy, button }: { icon: React.ReactNode; title: string; copy: string; button: string }) { return <article className="rounded-3xl border bg-card p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-500/10 text-rose-500">{icon}</span><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 min-h-15 text-sm leading-6 text-muted-foreground">{copy}</p><Button variant="outline" className="mt-5 rounded-xl">{button}</Button></article>; }
